'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace PassComplexObjectInCallback


    Partial Public Class [Default]

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' NameLabel control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected NameLabel As Global.DevExpress.Web.ASPxLabel

        ''' <summary>
        ''' Name control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Name As Global.DevExpress.Web.ASPxTextBox

        ''' <summary>
        ''' AgeLabel control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected AgeLabel As Global.DevExpress.Web.ASPxLabel

        ''' <summary>
        ''' Age control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Age As Global.DevExpress.Web.ASPxSpinEdit

        ''' <summary>
        ''' EmailLabel control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected EmailLabel As Global.DevExpress.Web.ASPxLabel

        ''' <summary>
        ''' Email control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Email As Global.DevExpress.Web.ASPxTextBox

        ''' <summary>
        ''' DateLabel control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected DateLabel As Global.DevExpress.Web.ASPxLabel

        ''' <summary>
        ''' ArrivalDate control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ArrivalDate As Global.DevExpress.Web.ASPxDateEdit

        ''' <summary>
        ''' ButtonsLabel control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ButtonsLabel As Global.DevExpress.Web.ASPxLabel

        ''' <summary>
        ''' btnUpdate control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btnUpdate As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' btnClear control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btnClear As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' callbackPanel control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected callbackPanel As Global.DevExpress.Web.ASPxCallbackPanel

        ''' <summary>
        ''' ErrorFrame control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ErrorFrame As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        ''' <summary>
        ''' PostedInfo control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected PostedInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        ''' <summary>
        ''' NameText control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected NameText As Global.DevExpress.Web.ASPxLabel

        ''' <summary>
        ''' AgeText control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected AgeText As Global.DevExpress.Web.ASPxLabel

        ''' <summary>
        ''' EmailText control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected EmailText As Global.DevExpress.Web.ASPxLabel

        ''' <summary>
        ''' ArrivalDateText control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ArrivalDateText As Global.DevExpress.Web.ASPxLabel
    End Class
End Namespace
